webapp/controllers/admin.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash
import os
from webapp.permission import admin_permission
from webapp.forms import RegisterLibrarianForm, EditLibrarianForm
from webapp.models import Librarian,db


admin_blueprint = Blueprint('admin',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','admin'),
    url_prefix='/admin')
@admin_blueprint.route('/')
@admin_permission
def main():
    return redirect(url_for('admin.get_librarians'))

@admin_blueprint.route('/register_librarian',methods=['GET','POST'])
@admin_permission
def register_librarian():
    form = RegisterLibrarianForm()
    if form.validate_on_submit():
        librarian = Librarian(form.ID.data,form.name.data,form.sex.data)
        librarian.set_password(form.password.data)
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.main'))
    return render_template('register_librarian.html',form=form)

@admin_blueprint.route('/delete_librarian',methods=['GET','POST'])

@admin_blueprint.route('/librarians')
@admin_permission
def get_librarians():
    libs = Librarian.query.all()

    return render_template('librarians.html',ts=libs)

@admin_blueprint.route('/edit_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def edit_librarian(ID):
    form = EditLibrarianForm()
    librarian = Librarian.query.filter_by(ID= ID).first()
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    if form.validate_on_submit():
        librarian.ID = form.ID.data
        librarian.name = form.name.data
        librarian.sex = form.sex.data
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.get_librarians'))
    form.ID.data = librarian.ID
    form.name.data = librarian.name
    form.sex.data = librarian.sex

    return render_template('edit_librarian.html',form=form)
        

@admin_blueprint.route('/delete_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def delete_librarian(ID):
    librarian = Librarian.query.filter_by(ID = ID).first()
    print(librarian)
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    db.session.delete(librarian)
    db.session.commit()
    flash('Succefful')
    return redirect(url_for('admin.get_librarians'))

webapp/controllers/librarian.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash,session,g
from webapp.models import System,Reader, Librarian, Book, Book_Copy, Transaction, db, FineChange, Income
from webapp.forms import SystemForm,IncomeForm,ReturnFineForm, EditReaderForm, ReaderSearchForm,RegisterReaderForm, AddBookForm, AddCopyForm,EditBookForm,BookForm, EditBookCopyForm,BookSearchForm,BorrowBookForm, ReturnBookForm, DeleteBook, DeleteEntity, Search
from flask_login import current_user

from webapp.constant import  TIME_OUT, TIME_IN,PAGINATION, BORROWED, DAMAGED, ON_THE_SHELF, LOST, DEALING
from webapp.extends import GetBook, download_picture, get_month, get_week, get_year
from webapp.permission import librarian_permission
import os
from datetime import timedelta, datetime
import re

from sqlalchemy import func

librarian_blueprint = Blueprint('librarian',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','librarian'),
    url_prefix='/librarian')

@librarian_blueprint.route('/')
@librarian_permission
def main():
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/books/<string:content>/<int:page>',methods=['GET','POST'])
@librarian_permission
def get_books(content='_',page=1):
    books = Book.query.paginate(page,PAGINATION)
    
    form = BookSearchForm()
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        elif form.methods.data==4:
            return redirect(url_for('librarian.get_book_copy',copy_id=int(form.content.data)))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books = books,content=content,endpoint='librarian.get_books',summary='')
@librarian_blueprint.route('/books/ISBN/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_ISBN(content,page):
    form = BookSearchForm()
    books = Book.query.filter_by(ISBN = content).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
        
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
@librarian_blueprint.route('/books/title/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_title(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.title.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_title',summary='this')
@librarian_blueprint.route('/books/author/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_author(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.author.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
    if form.validate_on_submit():
        if form.methods.data == 1:
            #ISBN
            #books = Book.query.filter(ISBN = form.content.data).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_ISBN',form.content.data,page=1))
        elif form.methods.data == 2:
            #books = Book.query.filter(Book.title.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_title',form.content.data,page=1))
        elif form.methods.data == 3:
            #books = Book.query.filter(Book.author.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_author',form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_author')

@librarian_blueprint.route('/book_copies/<int:book_id>')
@librarian_permission
def get_book_copies(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    book_copies = book.copies.all()
    return  render_template('book_copies.html',book_=book,book_copies = book_copies)

@librarian_blueprint.route('/book_copy/<int:copy_id>')
@librarian_permission
def get_book_copy(copy_id):
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    return render_template('book_copy.html',copy = copy)

@librarian_blueprint.route('/edit_book/<int:book_id>',methods=['GET','POST'])
@librarian_permission
def edit_book(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form = EditBookForm()
    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        book.press = form.press.data
        book.publish_date = form.publish_date.data
        book.ISBN = form.ISBN.data
        book.price = form.price.data

        if len(form.file.data.filename) != 0:
            form.file.data.save(os.path.join(current_app.root_path+'/static/picture',book.picture))
        book.summary = form.summary.data
        db.session.add(book)
        db.session.commit()
        flash('Successful')
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form.title.data = book.title
    form.author.data = book.author
    form.press.data = book.press
    form.publish_date.data = book.publish_date
    form.ISBN.data = book.ISBN
    form.price.data = book.price
    form.summary.data = book.summary

    return render_template('edit_book.html',form=form,picture=book.picture)

@librarian_blueprint.route('/damage_lost/<int:reader_id>/<float:fine>',methods=['GET','POST'])
@librarian_permission
def damage(reader_id,fine):
    reader = Reader.query.get(reader_id)
    if not reader:
        flash("Can't find this reader")
        return redirect(url_for('librarian.get_books',content='_',page=1))

    reader.fine += fine
    db.session.add(reader)
    db.session.commit()
    flash('Successful')
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/edit_copy/<int:copy_id>',methods=['GET','POST'])
@librarian_permission
def edit_copy(copy_id):
    form = EditBookCopyForm()
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    if form.validate_on_submit():
        if copy.status == BORROWED and form.status.data ==DAMAGED:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            damage_fine = System.query.get(1).damage_fine
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=damage_fine,header='Damage')
            
        if copy.status == BORROWED and form.status.data ==LOST:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            lost_fine = copy.book.price
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=lost_fine,header='Lost')

        copy.status = form.status.data
        copy.location = form.location.data

        db.session.add(copy)
        db.session.commit()
        flash('Successful')

webapp/controllers/main.py
from flask import Blueprint, render_template, redirect, url_for, flash
from webapp.forms import SearchForm, LoginForm, RegisterLibrarianForm
from webapp.constant import PAGINATION 
from webapp.models import Reader, Librarian, db, Admin
from flask_login import login_user, logout_user, current_user, login_required
from flask_login.mixins import AnonymousUserMixin
from webapp.permission import any_permission
from os import path

main_blueprint = Blueprint('main',__name__,
    static_folder=path.join(path.pardir,'static'),
    template_folder=path.join(path.pardir,'templates','main')
    ,url_prefix='/main')



@main_blueprint.route('/login',methods=['GET','POST'])
@any_permission
def login():
    # if current_user.is_authenticated:
    #     flash('You have logged in')
    #     return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        if form.role.data == 1:

            user = Reader.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 2:

            user = Librarian.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 3:

            user = Admin.query.filter_by(ID = form.id.data).first()
        else:
            user = None

        if user is not None:
            login_user(user,remember=form.remember.data)
            
            return redirect(url_for('main.index'))
    return render_template('login.html',form=form)




@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user() 
    return redirect(url_for('main.index'))

@main_blueprint.route('/',methods=['GET','POST'])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        method = form.methods.data
        content = form.content.data
        if method == 1:
            return redirect(url_for('result.result_title',content=content,page=1))
        elif method == 2:
            return redirect(url_for('result.result_author',content=content,page=1))
        elif method == 3:
            return redirect(url_for('result.result_ISBN',content=content))  
        else:
            return None
    return render_template('index.html',form=form)

webapp/controllers/reader.py
from flask import Blueprint, render_template
from os import path
from webapp.permission import reader_permission
from webapp.models import Transaction, Reader, Book_Copy
from flask_login import current_user
from webapp.constant import  TIME_IN, TIME_OUT, PAGINATION

reader_blueprint = Blueprint('reader',__name__,
    static_folder=path.join(path.pardir,'static'),
    template_folder=path.join(path.pardir,'templates','reader'),
    url_prefix='/reader')

@reader_blueprint.route('/main')
@reader_permission
def main():
    reader = Reader.query.get(current_user.reader_id)      
    
    
    return render_template('reader/main.html',reader=reader)

@reader_blueprint.route('/records/<int:reader_id>/<int:page>',methods=['GET','POST'])
@reader_permission
def get_records(reader_id,page=1):
    reader = current_user
    if not reader:
        flash("Can't find this reader")
        return redirect(url_for('reader.main'))
    transactions = reader.transactions.paginate(page,PAGINATION)
    res = list()
    for tran in transactions.items:
        copy = Book_Copy.query.get(tran.copy_id)
        res.append(dict({'Reader_ID':reader.ID,'Title': copy.book.title,'ISBN':copy.book.ISBN,
        'Copy_ID':copy.copy_id,'Borrow_Date':tran.borrow_date, 'Return_Date':tran.return_date,'Truely_Return_Date':tran.truely_return_date,
        'Status':tran.status}))
    return render_template('reader/records.html',transactions = transactions,res=res,reader_id=reader_id,endpoint='reader.get_records')
@reader_blueprint.route('/borrowing_books/<int:reader_id>',methods=['GET','POST'])
@reader_permission
def borrowing_books(reader_id):
    reader = current_user
    if not reader:
        flash("Can't find this reader")
        return redirect(url_for('reader.main'))
    trans = Transaction.query.filter_by(reader_id = reader_id, status=TIME_IN).all()
    if len(trans) > 2:
        
        flash('Error1')
        return redirect(url_for('reader.main'))
    copies = [Book_Copy.query.get(tran.copy_id) for tran in trans]
    for copy in copies:
        if copy is None:
            flash('Error2')
            return redirect(url_for('reader.main'))
    return render_template('reader/borrowing_books.html',copies = copies)

webapp/templates/reader/borrowing_books.html
{%extends 'reader/main.html'%}

{%block page_content%}

<div class='row'>
    <div class='col-lg-1'>

    </div>
    <div class='col-lg-10'>
        <table class='table table-hover'>
            <thead>
                <th class='col-lg-1'>No</th>
                <th class='col-lg-1'>Picture</th>
                <th class='col-lg-1'>Title</th>
                <th class='col-lg-1'>ISBN</th>
                <th class='col-lg-1'>Copy ID</th>
           
                <th class='col-lg-2'>Return Date</th>
            </thead>
            <tbody>
                {%for copy in copies%}
                    <tr>
                        <td class='col-lg-1'>
                            {{loop.index}}
                        </td>
                        <td class='col-lg-1'><a href='#' class='thumbnail'><img src='/static/picture/{{copy.book.picture}}'></a></td>
                        <td class='col-lg-1'>
                            {{copy.book.title}}
                        </td>
                        <td class='col-lg-1'>{{copy.book.ISBN}}</td>
                        <td class='col-lg-1'>{{copy.copy_id}}</td>
                        <td class='col-lg-1'>{{copy.return_date}}</td>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
    <div class='col-lg-1'>

    </div>
</div>

{%endblock%}

webapp/templates/reader/main.html
{%extends 'base.html'%}
{%from 'macros.html' import sex_to_view%}
{%block functions%}

<div class='navbar-collapse collapse'>
        
</div>

{%endblock%}
{%block page_content%}

<div class='row'>
    <div class='col-lg-1'>

    </div>
    <div class='col-lg-10'>
        <table class="table table-hover ">
                <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Sex</th>
                    <th>Fine</th>
                    <th>Deposite</th>
                    <th>Records</th>
                    <th>Borrowing Books</th>
            
                    
                </thead>
                <tbody>
                    
                    
                    
                    
                    <tr>

                        <td class='col-lg-1'>{{reader.ID}}</td>
                        <td class='col-lg-1'>{{reader.name}}</td>
                        <td class='col-lg-1'>{{sex_to_view(reader.sex)}}</td>
                        <td class='col-lg-1'>{{reader.fine}}</td>
                        <td class='col-lg-1'>{{reader.deposit}}</td>
                        <td class='col-lg-1'><a href='{{url_for('reader.get_records',reader_id = reader.reader_id,page=1)}}' >Click</a></td>
                        <td class='col-lg-1'><a href='{{url_for('reader.borrowing_books',reader_id = reader.reader_id)}}' >Click</a></td>
                        
                        
            
                       
                    </tr>
                   
                    
                </tbody>
            </table>
</div>
</div>

{%endblock%}

webapp/templates/reader/records.html
{%extends 'reader/main.html'%}
{%block page_content%}

<div class='row'>
    <div class='col-lg-1'>

    </div>
    <div class='col-lg-10'>
        <table class='table table-hover'>
            <thead>
                <th  class='col-lg-1'>No</th>
                <th  class='col-lg-1'>Reader ID</th>
                <th  class='col-lg-2'>Book Tile</th>
                <th  class='col-lg-1'>Book ISBN</th>
                <th  class='col-lg-1'>Copy ID</th>
                <th  class='col-lg-2'>Borrow Date</th>
                <th  class='col-lg-2'>Return Date</th>
                <th  class='col-lg-2'>Actually Return Date</th>
                <th  class='col-lg-1'>Status</th>
            </thead>
            <tbody>
                {%for transaction in res%}
                    <tr>
                        <td class='col-lg-1'>{{loop.index}}</td>
                        <td class='col-lg-1'>{{transaction['Reader_ID']}}</td>
                        <td class='col-lg-2'>{{transaction['Title']}}</td>
                        <td class='col-lg-1'>{{transaction['ISBN']}}</td>
                        <td class='col-lg-1'>{{transaction['Copy_ID']}}</td>
                        <td class='col-lg-2'>{{transaction['Borrow_Date']}}</td>
                        <td class='col-lg-2'>{{transaction['Return_Date']}}</td>
                        <td class='col-lg-2'>{{transaction['Truely_Return_Date']}}</td>
                        <td class='col-lg-1'>{{status_to_view(transaction['Status'])}}</td>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
        <div class='row'>
            {{render_pagination(transactions,reader_id,endpoint)}}                            
        </div>
    </div>
    
    <div class='col-lg-1'>

    </div>
</div>

{%endblock%}