webapp/controllers/admin.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash
import os
from webapp.permission import admin_permission
from webapp.forms import RegisterLibrarianForm, EditLibrarianForm
from webapp.models import Librarian,db


admin_blueprint = Blueprint('admin',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','admin'),
    url_prefix='/admin')
@admin_blueprint.route('/')
@admin_permission
def main():
    return redirect(url_for('admin.get_librarians'))

@admin_blueprint.route('/register_librarian',methods=['GET','POST'])
@admin_permission
def register_librarian():
    form = RegisterLibrarianForm()
    if form.validate_on_submit():
        librarian = Librarian(form.ID.data,form.name.data,form.sex.data)
        librarian.set_password(form.password.data)
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.main'))
    return render_template('register_librarian.html',form=form)

@admin_blueprint.route('/delete_librarian',methods=['GET','POST'])

@admin_blueprint.route('/librarians')
@admin_permission
def get_librarians():
    libs = Librarian.query.all()

    return render_template('librarians.html',ts=libs)

@admin_blueprint.route('/edit_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def edit_librarian(ID):
    form = EditLibrarianForm()
    librarian = Librarian.query.filter_by(ID= ID).first()
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    if form.validate_on_submit():
        librarian.ID = form.ID.data
        librarian.name = form.name.data
        librarian.sex = form.sex.data
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.get_librarians'))
    form.ID.data = librarian.ID
    form.name.data = librarian.name
    form.sex.data = librarian.sex

    return render_template('edit_librarian.html',form=form)
        

@admin_blueprint.route('/delete_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def delete_librarian(ID):
    librarian = Librarian.query.filter_by(ID = ID).first()
    print(librarian)
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    db.session.delete(librarian)
    db.session.commit()
    flash('Succefful')
    return redirect(url_for('admin.get_librarians'))

webapp/controllers/librarian.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash,session,g
from webapp.models import System,Reader, Librarian, Book, Book_Copy, Transaction, db, FineChange, Income
from webapp.forms import SystemForm,IncomeForm,ReturnFineForm, EditReaderForm, ReaderSearchForm,RegisterReaderForm, AddBookForm, AddCopyForm,EditBookForm,BookForm, EditBookCopyForm,BookSearchForm,BorrowBookForm, ReturnBookForm, DeleteBook, DeleteEntity, Search
from flask_login import current_user

from webapp.constant import  TIME_OUT, TIME_IN,PAGINATION, BORROWED, DAMAGED, ON_THE_SHELF, LOST, DEALING
from webapp.extends import GetBook, download_picture, get_month, get_week, get_year
from webapp.permission import librarian_permission
import os
from datetime import timedelta, datetime
import re

from sqlalchemy import func

librarian_blueprint = Blueprint('librarian',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','librarian'),
    url_prefix='/librarian')

@librarian_blueprint.route('/')
@librarian_permission
def main():
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/books/<string:content>/<int:page>',methods=['GET','POST'])
@librarian_permission
def get_books(content='_',page=1):
    books = Book.query.paginate(page,PAGINATION)
    
    form = BookSearchForm()
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        elif form.methods.data==4:
            return redirect(url_for('librarian.get_book_copy',copy_id=int(form.content.data)))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books = books,content=content,endpoint='librarian.get_books',summary='')
@librarian_blueprint.route('/books/ISBN/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_ISBN(content,page):
    form = BookSearchForm()
    books = Book.query.filter_by(ISBN = content).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
        
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
@librarian_blueprint.route('/books/title/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_title(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.title.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_title',summary='this')
@librarian_blueprint.route('/books/author/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_author(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.author.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
    if form.validate_on_submit():
        if form.methods.data == 1:
            #ISBN
            #books = Book.query.filter(ISBN = form.content.data).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_ISBN',form.content.data,page=1))
        elif form.methods.data == 2:
            #books = Book.query.filter(Book.title.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_title',form.content.data,page=1))
        elif form.methods.data == 3:
            #books = Book.query.filter(Book.author.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_author',form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_author')

@librarian_blueprint.route('/book_copies/<int:book_id>')
@librarian_permission
def get_book_copies(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    book_copies = book.copies.all()
    return  render_template('book_copies.html',book_=book,book_copies = book_copies)

@librarian_blueprint.route('/book_copy/<int:copy_id>')
@librarian_permission
def get_book_copy(copy_id):
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    return render_template('book_copy.html',copy = copy)

@librarian_blueprint.route('/edit_book/<int:book_id>',methods=['GET','POST'])
@librarian_permission
def edit_book(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form = EditBookForm()
    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        book.press = form.press.data
        book.publish_date = form.publish_date.data
        book.ISBN = form.ISBN.data
        book.price = form.price.data

        if len(form.file.data.filename) != 0:
            form.file.data.save(os.path.join(current_app.root_path+'/static/picture',book.picture))
        book.summary = form.summary.data
        db.session.add(book)
        db.session.commit()
        flash('Successful')
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form.title.data = book.title
    form.author.data = book.author
    form.press.data = book.press
    form.publish_date.data = book.publish_date
    form.ISBN.data = book.ISBN
    form.price.data = book.price
    form.summary.data = book.summary

    return render_template('edit_book.html',form=form,picture=book.picture)

@librarian_blueprint.route('/damage_lost/<int:reader_id>/<float:fine>',methods=['GET','POST'])
@librarian_permission
def damage(reader_id,fine):
    reader = Reader.query.get(reader_id)
    if not reader:
        flash("Can't find this reader")
        return redirect(url_for('librarian.get_books',content='_',page=1))

    reader.fine += fine
    db.session.add(reader)
    db.session.commit()
    flash('Successful')
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/edit_copy/<int:copy_id>',methods=['GET','POST'])
@librarian_permission
def edit_copy(copy_id):
    form = EditBookCopyForm()
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    if form.validate_on_submit():
        if copy.status == BORROWED and form.status.data ==DAMAGED:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            damage_fine = System.query.get(1).damage_fine
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=damage_fine,header='Damage')
            
        if copy.status == BORROWED and form.status.data ==LOST:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            lost_fine = copy.book.price
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=lost_fine,header='Lost')

        copy.status = form.status.data
        copy.location = form.location.data

        db.session.add(copy)
        db.session.commit()
        flash('Successful')

webapp/controllers/main.py
from flask import Blueprint, render_template, redirect, url_for, flash
from webapp.forms import SearchForm, LoginForm, RegisterLibrarianForm
from webapp.constant import PAGINATION 
from webapp.models import Reader, Librarian, db, Admin
from flask_login import login_user, logout_user, current_user, login_required
from flask_login.mixins import AnonymousUserMixin
from webapp.permission import any_permission
from os import path

main_blueprint = Blueprint('main',__name__,
    static_folder=path.join(path.pardir,'static'),
    template_folder=path.join(path.pardir,'templates','main')
    ,url_prefix='/main')



@main_blueprint.route('/login',methods=['GET','POST'])
@any_permission
def login():
    # if current_user.is_authenticated:
    #     flash('You have logged in')
    #     return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        if form.role.data == 1:

            user = Reader.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 2:

            user = Librarian.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 3:

            user = Admin.query.filter_by(ID = form.id.data).first()
        else:
            user = None

        if user is not None:
            login_user(user,remember=form.remember.data)
            
            return redirect(url_for('main.index'))
    return render_template('login.html',form=form)




@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user() 
    return redirect(url_for('main.index'))

@main_blueprint.route('/',methods=['GET','POST'])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        method = form.methods.data
        content = form.content.data
        if method == 1:
            return redirect(url_for('result.result_title',content=content,page=1))
        elif method == 2:
            return redirect(url_for('result.result_author',content=content,page=1))
        elif method == 3:
            return redirect(url_for('result.result_ISBN',content=content))  
        else:
            return None
    return render_template('index.html',form=form)

webapp/controllers/result.py
from flask import Blueprint, render_template, flash
from webapp.constant import PAGINATION
from webapp.models import Book, Book_Copy
from os import path

result_blueprint = Blueprint('result',__name__,
    static_folder=path.join(path.pardir,'static'),
    template_folder=path.join(path.pardir,'templates','result')
    ,url_prefix='/result')

@result_blueprint.route('/title/<string:content>/<int:page>')
def result_title(content,page=1):
    books = Book.query.filter(Book.title.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
    return render_template('result.html', content=content,books=books, endpoint='result.result_title')

@result_blueprint.route('/author/<string:content>/<int:page>')
def result_author(content,page=1):
    books = Book.query.filter(Book.author.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
    return render_template('result.html', content=content,books=books, endpoint='result.result_author')

@result_blueprint.route('/ISBN/<string:content>')
def result_ISBN(content,page=1):
    book = Book.query.filter_by(ISBN=content).paginate(page,PAGINATION)
    if len(book.items) == 0:
        flash("No Results")
    return render_template('result.html',content=content,books=book, endpoint='result.result_author')

@result_blueprint.route('/entity/<int:book_id>')
def result_entity(book_id):
    book_info = Book.query.filter_by(book_id=book_id).paginate(1,1)
    books = Book_Copy.query.filter_by(book_id=book_id).all()
    if len(books) == 0:
        flash("No Results")
    return render_template('entity.html', book_info=book_info, books=books)
    

webapp/templates/base.html
{%extends 'bootstrap/base.html'%}\
{%import 'bootstrap/wtf.html' as wtf%}
{%from 'macros.html' import render_pagination, render_pagination2,render_field, modal, trigger,status_to_view,sex_to_view%}
{%block head%}
{{super()}}
<link rel='shortcut icon' href="{{url_for('static',filename='img/books.ico')}}" type='image/x-icon'>
<link rel='icon' href="{{url_for('static',filename='img/books.ico')}}" type='image/x-icon'>
<script type='text/javascript' src="{{url_for('static',filename='js/jquery-3.2.1.min.js')}}"></script>

<style>tbody tr td{
        vertical-align: middle !important;
    }

    </style>

{%endblock%}
{%block title%}Xi Dian Library{%endblock%}
{%block navbar%}
<div class='navbar navbar-inverse' role='navigation'>
    <div class='container'>
        <button type='button' class='navbar-toggle'
            data-toggle='collapse' data-target='.navbar-collapse'>
            <span class='sr-only'>Toggle navigation</span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
        </button>
        <a class='navbar-brand' href='/'>Xi Dian Library</a>
        <ul class='nav navbar-nav navbar-right'>
                {%if current_user.is_authenticated %}
                    
                    {%if current_user.is_admin()%}
                        <li><a href='{{url_for('admin.main')}}'><strong>Current User : </strong>{{current_user.ID}}</a></li>    
                    {%elif current_user.is_reader()%}
                        <li><a href='{{url_for('reader.main')}}'><strong>Current User : </strong>{{current_user.ID}}</a></li>
                    {%elif current_user.is_librarian()%}
                        <li><a href='{{url_for('librarian.main')}}'><strong>Current User : </strong>{{current_user.ID}}</a></li>
                     
                    {%endif%}
                    
                    <li><a href='{{url_for('main.logout')}}'>Log Out</a></li>
                {%else%}
                    <li><a href='{{url_for('main.login')}}'>Log In</a></li>

                {%endif%}
        </ul>
        {%block functions%}
            
        {%endblock%}
    </div>
</div>
{%endblock%}

{%block content%}
<div class='container'>
    {%block flash%}
        {%for message in get_flashed_messages()%}
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
                </button>
                {{message}}
            </div>
        {%endfor%}
    {%endblock%}
    {%block page_content%}{%endblock%}
</div>
{%endblock%}

webapp/templates/macros.html
{%macro render_pagination(pagination, content, endpoint)%}
<nav>
    <ul class='pagination'>
        <li>
            {%if pagination.has_prev%}
                <a href='{{url_for(endpoint,content=content,page=pagination.prev().page)}}' aria-label='Previous'>
                    <span aria-hidden='true'>&laquo;</span>
                </a>
            {%else%}
                <!-- <a href='' aria-label='Previous' >
                    <span aria-hidden='true'>&laquo;</span>
                </a> -->
            {%endif%}
        </li>
        {%for page in pagination.iter_pages()%}
            {%if page %}
                {%if page != pagination.page %}
                    <li class='disable'>
                        <a href='{{ url_for(endpoint,content=content,page=page)}}'>
                            {{page}}
                        </a>
                    </li>
                {%else%}
                    <li class='active'><a href="">{{page}}</a></li>
                {%endif%}
            {%else%}
                <li><a>...</a></li>
            {%endif%}
        {%endfor%}
        <li>
            {%if pagination.has_next%}
            <a href='{{url_for(endpoint,content=content,page=pagination.next().page)}}' aria-label='Next'>
                <span aria-hidden='true'>&raquo;</span>
            </a>
            {%else%}
            <!-- <a href='' aria-label='Next'>
                    <span aria-hidden='true'>&raquo;</span>
            </a> -->
            {%endif%}
        </li>
    </ul>
</nav>     
{%endmacro%}
{% macro render_field(field) %}
<div class='row'>
     {{ field.label }}
</div>
<div class='row'>
    {{ field(**kwargs)|safe }}
</div>
{% endmacro %}
{%macro book_result(books)%}

        <table class="table table-hover ">
            <thead>
                <th>Picture</th>
                <th>Title</th>
                <th>Author</th>
                <th>Press</th>
                <th>Publish Date</th>
                <th>ISBN</th>
                <th>Price</th>
                <th>Summary</th>
            </thead>
            <tbody>
                
                {%for book in books.items%}
                <tr>
                    <td class='col-lg-1'><a href='{{url_for('result.result_entity',book_id=book.book_id)}}' class='thumbnail'><img src='/static/picture/{{book.picture}}'></a></td>
                    <td class='col-lg-1'><a href='{{url_for('result.result_entity',book_id=book.book_id)}}'>{{book.title}}</a></td>
                    <td class='col-lg-1'><a href='{{url_for('result.result_author',content=book.author,page=1)}}'>{{book.author}}</a></td>
                    <td class='col-lg-1'>{{book.press}}</td>
                    <td class='col-lg-1'>{{book.publish_date}}</td>
                    <td class='col-lg-1'>{{book.ISBN}}</td>
                    <td class='col-lg-1'>{{book.price}}</td>
                    <td class='col-lg-3'>
                            <a href="#" class="tooltip-test" data-toggle="tooltip" title="{{book.summary}}">{{book.summary[:20]}}</a>
                    </td>
                </tr>
                {%endfor%}
                
            </tbody>
        </table>


{%endmacro%}
{%macro reader_info(reader)%}
<table class='table table-hover'>
    <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Sex</th>
        <th>Fine</th>
        <th>Deposit</th>
    </thead>
    <tbody>
        <tr>
            <td>{{reader.ID}}</td>
            <td>{{reader.name}}</td>
            <td>
                {%if reader.sex==1%}
                male
                {%else%}
                    female
                {%endif%}
            </td>
            <td>{{reader.fine}}</td>
            <td>{{reader.deposit}}</td>
        </tr>
    </tbody>
</table>
{%endmacro%}
{%macro status_to_view(status)%}
{%if status == 1%}
    On the shelf
{%elif status==2%}
    Borrowed
{%elif status==8%}
    Damaged
{%elif status==16%}
    Lost
{%elif status==3%}
    Time Out
{%elif status==4%}
    Time In
{%else%}
    Arranging
{%endif%}
{%endmacro%}

{%macro sex_to_view(sex)%}

{%if sex==1%}
    Male
{%else%}
    Female
{%endif%}

{%endmacro%}

{%macro my_table(ths,ts,urls)%}
<div class='row'>
        <div class='col-lg-2'></div>
        <div class='col-lg-8'>
        <table class='table table-hover'>
            <thead>
                {%for t in ths%}
                <th class='col-lg-1'>{{t}}</th>
                {%endfor%}
                
            </thead>
            <tbody>
                {% for t in ts %}
                    <tr>
                        {%for tt in t%}
                        {%if tt != 'Edit' and tt != 'Delete'%}
                        <td class='col-lg-1'>{{tt}}</td>
                        {%else%}
                            {%if tt == 'Edit'%}
                            <td class='col-lg-1'><a href='{{url_for('{{urls[0]}}')}}'>tt</a></td>
                            {%else%}
                            <td class='col-lg-1'><a href='{{url_for('{{urls[1]}}')}}'>tt</a></td>
                            {%endif%}
                        {%endif%}
                        {%endfor%}
                      
                    </tr>
    
                {%endfor%}
            </tbody>
        </table>
        </div>
        <div class='col-lg-2'></div>
    </div>
{%endmacro%}
{%macro trigger(size,id,button_name)%}
<button class="btn btn-default btn-{{size}}" data-toggle='modal' data-target='#{{id}}'>
        <a >{{button_name}}</a>
</button>
{%endmacro%}

{%macro modal(fade, id,header,body,url)%}
<div class="modal {{fade}}" id="{{id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        {{header}}}
                    </h4>
                </div>
               <div class='modal-body'>
                   {{body}}

               </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal" href='#' role='button'>Close
                    </a>
                    <a class="btn btn-default"  href="{{url}}" role='button'>Submit
                    </a>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
{%endmacro%}



{%macro render_pagination2(pagination,reader_id, endpoint)%}
<nav>
    <ul class='pagination'>
        <li>
            {%if pagination.has_prev%}
                <a href='{{url_for(endpoint,reader_id=reader_id,page=pagination.prev().page)}}' aria-label='Previous'>
                    <span aria-hidden='true'>&laquo;</span>
                </a>
            {%else%}
                <!-- <a href='' aria-label='Previous' >
                    <span aria-hidden='true'>&laquo;</span>
                </a> -->
            {%endif%}
        </li>
        {%for page in pagination.iter_pages()%}
            {%if page %}
                {%if page != pagination.page %}
                    <li class='disable'>
                        <a href='{{ url_for(endpoint,reader_id=reader_id,page=page)}}'>
                            {{page}}
                        </a>
                    </li>
                {%else%}
                    <li class='active'><a href="">{{page}}</a></li>
                {%endif%}
            {%else%}
                <li><a>...</a></li>
            {%endif%}
        {%endfor%}
        <li>
            {%if pagination.has_next%}
            <a href='{{url_for(endpoint,reader_id=reader_id,page=pagination.next().page)}}' aria-label='Next'>
                <span aria-hidden='true'>&raquo;</span>
            </a>
            {%else%}
            <!-- <a href='' aria-label='Next'>
                    <span aria-hidden='true'>&raquo;</span>
            </a> -->
            {%endif%}
        </li>
    </ul>
</nav>     
{%endmacro%}