webapp/controllers/admin.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash
import os
from webapp.permission import admin_permission
from webapp.forms import RegisterLibrarianForm, EditLibrarianForm
from webapp.models import Librarian,db


admin_blueprint = Blueprint('admin',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','admin'),
    url_prefix='/admin')
@admin_blueprint.route('/')
@admin_permission
def main():
    return redirect(url_for('admin.get_librarians'))

@admin_blueprint.route('/register_librarian',methods=['GET','POST'])
@admin_permission
def register_librarian():
    form = RegisterLibrarianForm()
    if form.validate_on_submit():
        librarian = Librarian(form.ID.data,form.name.data,form.sex.data)
        librarian.set_password(form.password.data)
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.main'))
    return render_template('register_librarian.html',form=form)

@admin_blueprint.route('/delete_librarian',methods=['GET','POST'])

@admin_blueprint.route('/librarians')
@admin_permission
def get_librarians():
    libs = Librarian.query.all()

    return render_template('librarians.html',ts=libs)

@admin_blueprint.route('/edit_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def edit_librarian(ID):
    form = EditLibrarianForm()
    librarian = Librarian.query.filter_by(ID= ID).first()
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    if form.validate_on_submit():
        librarian.ID = form.ID.data
        librarian.name = form.name.data
        librarian.sex = form.sex.data
        db.session.add(librarian)
        db.session.commit()
        return redirect(url_for('admin.get_librarians'))
    form.ID.data = librarian.ID
    form.name.data = librarian.name
    form.sex.data = librarian.sex

    return render_template('edit_librarian.html',form=form)
        

@admin_blueprint.route('/delete_librarian/<string:ID>',methods=['GET','POST'])
@admin_permission
def delete_librarian(ID):
    librarian = Librarian.query.filter_by(ID = ID).first()
    print(librarian)
    if not librarian:
        flash("Can't find this librarian")
        return redirect(url_for('admin.get_librarians'))
    db.session.delete(librarian)
    db.session.commit()
    flash('Succefful')
    return redirect(url_for('admin.get_librarians'))

webapp/controllers/librarian.py
from flask import Blueprint, render_template, url_for, redirect, current_app, flash,session,g
from webapp.models import System,Reader, Librarian, Book, Book_Copy, Transaction, db, FineChange, Income
from webapp.forms import SystemForm,IncomeForm,ReturnFineForm, EditReaderForm, ReaderSearchForm,RegisterReaderForm, AddBookForm, AddCopyForm,EditBookForm,BookForm, EditBookCopyForm,BookSearchForm,BorrowBookForm, ReturnBookForm, DeleteBook, DeleteEntity, Search
from flask_login import current_user

from webapp.constant import  TIME_OUT, TIME_IN,PAGINATION, BORROWED, DAMAGED, ON_THE_SHELF, LOST, DEALING
from webapp.extends import GetBook, download_picture, get_month, get_week, get_year
from webapp.permission import librarian_permission
import os
from datetime import timedelta, datetime
import re

from sqlalchemy import func

librarian_blueprint = Blueprint('librarian',__name__,
    static_folder=os.path.join(os.path.pardir,'static'),
    template_folder=os.path.join(os.path.pardir,'templates','librarian'),
    url_prefix='/librarian')

@librarian_blueprint.route('/')
@librarian_permission
def main():
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/books/<string:content>/<int:page>',methods=['GET','POST'])
@librarian_permission
def get_books(content='_',page=1):
    books = Book.query.paginate(page,PAGINATION)
    
    form = BookSearchForm()
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        elif form.methods.data==4:
            return redirect(url_for('librarian.get_book_copy',copy_id=int(form.content.data)))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books = books,content=content,endpoint='librarian.get_books',summary='')
@librarian_blueprint.route('/books/ISBN/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_ISBN(content,page):
    form = BookSearchForm()
    books = Book.query.filter_by(ISBN = content).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
        
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
        
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
@librarian_blueprint.route('/books/title/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_title(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.title.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
    if form.validate_on_submit():
        if form.methods.data == 1:
            return redirect(url_for('librarian.get_books_ISBN',content=form.content.data,page=1))
        elif form.methods.data == 2:
            return redirect(url_for('librarian.get_books_title',content=form.content.data,page=1))
        elif form.methods.data == 3:
            return redirect(url_for('librarian.get_books_author',content=form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_title',summary='this')
@librarian_blueprint.route('/books/author/<string:content>/<int:page>',methods=['POST','GET'])
@librarian_permission
def get_books_author(content,page):
    form  = BookSearchForm()
    books = Book.query.filter(Book.author.like('%'+content+'%')).paginate(page,PAGINATION)
    if len(books.items) == 0:
        flash("No Results")
        return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_ISBN',flag=True)
    if form.validate_on_submit():
        if form.methods.data == 1:
            #ISBN
            #books = Book.query.filter(ISBN = form.content.data).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_ISBN',form.content.data,page=1))
        elif form.methods.data == 2:
            #books = Book.query.filter(Book.title.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_title',form.content.data,page=1))
        elif form.methods.data == 3:
            #books = Book.query.filter(Book.author.like('%'+form.content.data+'%')).paginate(page,PAGINATION)
            return redirect(url_for('librarian.get_books_author',form.content.data,page=1))
        else:
            flash('Error')
            books = None
    return render_template('books.html',form=form,books=books,content=content,endpoint='librarian.get_books_author')

@librarian_blueprint.route('/book_copies/<int:book_id>')
@librarian_permission
def get_book_copies(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    book_copies = book.copies.all()
    return  render_template('book_copies.html',book_=book,book_copies = book_copies)

@librarian_blueprint.route('/book_copy/<int:copy_id>')
@librarian_permission
def get_book_copy(copy_id):
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    return render_template('book_copy.html',copy = copy)

@librarian_blueprint.route('/edit_book/<int:book_id>',methods=['GET','POST'])
@librarian_permission
def edit_book(book_id):
    book = Book.query.get(book_id)
    if not book:
        flash("Can't find this book")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form = EditBookForm()
    if form.validate_on_submit():
        book.title = form.title.data
        book.author = form.author.data
        book.press = form.press.data
        book.publish_date = form.publish_date.data
        book.ISBN = form.ISBN.data
        book.price = form.price.data

        if len(form.file.data.filename) != 0:
            form.file.data.save(os.path.join(current_app.root_path+'/static/picture',book.picture))
        book.summary = form.summary.data
        db.session.add(book)
        db.session.commit()
        flash('Successful')
        return redirect(url_for('librarian.get_books',content='_',page=1))
    form.title.data = book.title
    form.author.data = book.author
    form.press.data = book.press
    form.publish_date.data = book.publish_date
    form.ISBN.data = book.ISBN
    form.price.data = book.price
    form.summary.data = book.summary

    return render_template('edit_book.html',form=form,picture=book.picture)

@librarian_blueprint.route('/damage_lost/<int:reader_id>/<float:fine>',methods=['GET','POST'])
@librarian_permission
def damage(reader_id,fine):
    reader = Reader.query.get(reader_id)
    if not reader:
        flash("Can't find this reader")
        return redirect(url_for('librarian.get_books',content='_',page=1))

    reader.fine += fine
    db.session.add(reader)
    db.session.commit()
    flash('Successful')
    return redirect(url_for('librarian.get_books',content='_',page=1))


@librarian_blueprint.route('/edit_copy/<int:copy_id>',methods=['GET','POST'])
@librarian_permission
def edit_copy(copy_id):
    form = EditBookCopyForm()
    copy = Book_Copy.query.get(copy_id)
    if not copy:
        flash("Can't find this copy")
        return redirect(url_for('librarian.get_books',content='_',page=1))
    if form.validate_on_submit():
        if copy.status == BORROWED and form.status.data ==DAMAGED:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            damage_fine = System.query.get(1).damage_fine
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=damage_fine,header='Damage')
            
        if copy.status == BORROWED and form.status.data ==LOST:
            tran = Transaction.query.filter_by(copy_id=copy.copy_id,status=TIME_IN).first()
            if not tran:
                flash('Error1')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            reader = Reader.query.get(tran.reader_id)
            if not reader:
                flash('Error2')
                return redirect(url_for('librarian.edit_copy',copy_id=copy.copy_id))
            lost_fine = copy.book.price
            return render_template('damage.html',form=form,copy=copy,reader=reader,fine=lost_fine,header='Lost')

        copy.status = form.status.data
        copy.location = form.location.data

        db.session.add(copy)
        db.session.commit()
        flash('Successful')

webapp/controllers/main.py
from flask import Blueprint, render_template, redirect, url_for, flash
from webapp.forms import SearchForm, LoginForm, RegisterLibrarianForm
from webapp.constant import PAGINATION 
from webapp.models import Reader, Librarian, db, Admin
from flask_login import login_user, logout_user, current_user, login_required
from flask_login.mixins import AnonymousUserMixin
from webapp.permission import any_permission
from os import path

main_blueprint = Blueprint('main',__name__,
    static_folder=path.join(path.pardir,'static'),
    template_folder=path.join(path.pardir,'templates','main')
    ,url_prefix='/main')



@main_blueprint.route('/login',methods=['GET','POST'])
@any_permission
def login():
    # if current_user.is_authenticated:
    #     flash('You have logged in')
    #     return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        if form.role.data == 1:

            user = Reader.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 2:

            user = Librarian.query.filter_by(ID=form.id.data).first()
        elif form.role.data == 3:

            user = Admin.query.filter_by(ID = form.id.data).first()
        else:
            user = None

        if user is not None:
            login_user(user,remember=form.remember.data)
            
            return redirect(url_for('main.index'))
    return render_template('login.html',form=form)




@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user() 
    return redirect(url_for('main.index'))

@main_blueprint.route('/',methods=['GET','POST'])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        method = form.methods.data
        content = form.content.data
        if method == 1:
            return redirect(url_for('result.result_title',content=content,page=1))
        elif method == 2:
            return redirect(url_for('result.result_author',content=content,page=1))
        elif method == 3:
            return redirect(url_for('result.result_ISBN',content=content))  
        else:
            return None
    return render_template('index.html',form=form)

webapp/main.py
from flask import Flask, render_template, url_for, redirect
from webapp.config import DevConfig
from webapp.models import db,Income
from flask_bootstrap import Bootstrap
from webapp.extends import bcrypt, login_manager,get_month,get_week,get_year
from flask_apscheduler import APScheduler
from datetime import datetime

from webapp.controllers.main import main_blueprint 
from webapp.controllers.result import result_blueprint
from webapp.controllers.librarian import librarian_blueprint
from webapp.controllers.reader import reader_blueprint
from webapp.controllers.admin import admin_blueprint


def income():
    
    with db.app.app_context():
        date = datetime.date(datetime.now())
        if not Income.query.filter_by(date=date).first() :
            inco = Income(date,get_year(date),get_month(date),get_week(date),0.0)
            
         
            db.session.add(inco)
            db.session.commit()

def create_app(object_name):
    scheduler = APScheduler()

    app = Flask(__name__)
    app.config.from_object(object_name)

    db.app=app
    db.init_app(app)
    Bootstrap(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    scheduler.init_app(app)

    app.register_blueprint(admin_blueprint)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(result_blueprint)
    app.register_blueprint(librarian_blueprint)
    app.register_blueprint(reader_blueprint)
    
    @app.route('/')
    def index():
        return redirect(url_for('main.index'))
    scheduler.start()
    return app

if __name__=='__main__':
    
    scheduler = APScheduler()

    app = Flask(__name__)
    app.config.from_object(object_name)

    db.app=app
    db.init_app(app)
    Bootstrap(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    scheduler.init_app(app)

    app.register_blueprint(admin_blueprint)
    app.register_blueprint(main_blueprint)
    app.register_blueprint(result_blueprint)
    app.register_blueprint(librarian_blueprint)
    app.register_blueprint(reader_blueprint)
    
    @app.route('/')
    def index():
        return redirect(url_for('main.index'))
    scheduler.start()
    app.run()

webapp/templates/librarian/book_copies.html
{%extends 'librarian/main.html'%}
{%from 'macros.html' import status_to_view%}
{%block page_content%}

<div class='row'>
    <div class='col-lg-1'></div>
    <div class = 'col-lg-10'>
        <div class='row'>
                <table class="table table-hover ">
                        <thead>
                            <th>Picture</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Press</th>
                            <th>Publish Date</th>
                            <th>ISBN</th>
                            <th>Price</th>
                            <th>Summary</th>
                    
                            <th>Operations</th>
                        </thead>
                        <tbody>
                            
                            
                            
                            <tr>
                                <td class='col-lg-1'><a href='{{url_for('librarian.get_book_copies',book_id=book_.book_id)}}' class='thumbnail'><img src='/static/picture/{{book_.picture}}'></a></td>
                                <td class='col-lg-1'><a href='{{url_for('librarian.get_book_copies',book_id=book_.book_id)}}'>{{book_.title}}</a></td>
                                <td class='col-lg-1'>{{book_.author}}</td>
                                <td class='col-lg-1'>{{book_.press}}</td>
                                <td class='col-lg-1'>{{book_.publish_date}}</td>
                                <td class='col-lg-1'>{{book_.ISBN}}</td>
                                <td class='col-lg-1'>{{book_.price}}</td>
                                <td class='col-lg-3'>
                                        <a href="#" class="tooltip-test" data-toggle="tooltip" title="{{book_.summary}}">{{book_.summary[:20]}}</a>
                                    
                                </td>
                    
                                <td class='col-lg-2'>
                                    <button class='btn btn-default btn-xs'>
                                        <a href="{{url_for('librarian.edit_book',book_id=book_.book_id)}}">Edit</a>
                                    </button>
                                    
                                    <button class='btn btn-default btn-xs'>
                                        <a href='{{url_for('librarian.add_copy',book_id=book_.book_id)}}'>Add</a>
                                    </button>
                                   
                                    <button class="btn btn-default btn-xs" data-toggle='modal' data-target='#delete{{book_.book_id}}'>
                                            <a>Delete</a>
                                    </button>
                                    
                                    <div class="modal fade" id="delete{{book_.book_id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                            &times;
                                                        </button>
                                                        <h4 class="modal-title" id="myModalLabel">
                                                            Confirmed to delete?
                                                        </h4>
                                                    </div>
                                                   <div class='modal-body'>
                                                       <table>
                                                           <thead>
                                                                
                                                                <th>Title</th>
                                                                <th>Author</th>
                                                                <th>Press</th>
                                                                <th>Publish Date</th>
                                                                <th>ISBN</th>
                                                                <th>Price</th>
                                                                <th>Summary</th>
                                                           </thead>
                                                           <tbody>
                                                               <tr>
                                                                    
                                                                    <td class='col-lg-1'><a href='{{url_for('librarian.get_book_copies',book_id=book_.book_id)}}'>{{book_.title}}</a></td>
                                                                    <td class='col-lg-1'>{{book_.author}}</td>
                                                                    <td class='col-lg-1'>{{book_.press}}</td>
                                                                    <td class='col-lg-1'>{{book_.publish_date}}</td>
                                                                    <td class='col-lg-1'>{{book_.ISBN}}</td>
                                                                    <td class='col-lg-1'>{{book_.price}}</td>
                                                                    <td class='col-lg-3'>
                                                                            <a href="#" class="tooltip-test" data-toggle="tooltip" title="{{book_.summary}}">{{book_.summary[:20]}}</a>
                                                                    </td>
                                                               </tr>
                                                           </tbody>
                                                       </table>

                                                   </div>
                                                    <div class="modal-footer">
                                                        <a class="btn btn-default" data-dismiss="modal" href='#' role='button'>Close
                                                        </a>
                                                        <a class="btn btn-default"  href="{{url_for('librarian.delete_book',book_id=book_.book_id)}}" role='button'>Delete
                                                        </a>
                                                    </div>
                                                </div><!-- /.modal-content -->
                                            </div><!-- /.modal -->
                                            
                                        </div>
                                    
                                </td>
                            </tr>
                            
                            
                        </tbody>
                    </table>
        </div>
        <div class='row'>
        <table class="table table-hover ">
            <thead>
                <th>No</th>
                <th>Copy ID</th>
                <th>Status</th>
                <th>Return Date</th>
                <th>Location</th>
                <th>Operations</th>
            </thead>
            <tbody>
                {%for book in book_copies%}
                <tr>
                    <td class='col-lg-2'>{{loop.index}}</td>
                    <td class='col-lg-2'>{{book.copy_id}}</td>
                    <td class='col-lg-2'>{{status_to_view(book.status)}}</td>
                    <td class='col-lg-2'>{{book.return_date}}</td>
                    <td class='col-lg-2'>{{book.location}}</td>
                    <td class='col-lg-2'>
                        <button class='btn btn-default btn-sm'>
                            <a href='{{url_for('librarian.edit_copy',copy_id=book.copy_id)}}'>Edit</a>
                        </button>
                        <button class="btn btn-default btn-sm" data-toggle='modal' data-target='#delete{{book.copy_id}}'>
                                <a>Delete</a>
                        </button>
                
                        <div class="modal fade" id="delete{{book.copy_id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                &times;
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel">
                                                Confirmed to delete?
                                            </h4>
                                        </div>
                                       <div class='modal-body'>
                                            <table class="table table-hover ">
                                                    <thead>
                                                       
                                                        <th>Copy ID</th>
                                                        <th>Status</th>
                                                        <th>Return Date</th>
                                                        <th>Location</th>
                                                       
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                                <td class='col-lg-2'>{{book.copy_id}}</td>
                                                                <td class='col-lg-2'>{{status_to_view(book.status)}}</td>
                                                                <td class='col-lg-2'>{{book.return_date}}</td>
                                                                <td class='col-lg-2'>{{book.location}}</td>
                                                        </tr>
                                                    </tbody>
                                            </table>
                                       </div>
                                        <div class="modal-footer">
                                            <a class="btn btn-default" data-dismiss="modal" href='#' role='button'>Close
                                            </a>
                                            <a class="btn btn-default" href="{{url_for('librarian.delete_copy',copy_id=book.copy_id)}}" role='button'>Delete
                                            </a>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal -->
                            </div>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
    </div>
</div>

{%endblock%}

webapp/templates/librarian/damage.html
{%extends 'librarian/main.html'%}

{%block page_content%}

<div class='row'>
</br></br>
    <div class='col-lg-4'>
            
    </div>
    <div class='col-lg-4'>
            <strong>Copy ID : {{copy.copy_id}}</strong>
        {{wtf.quick_form(form)}}
        
        <script>
                $(function () { $('#myModal').modal({keyboard: true})});
        </script>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                &times;
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                {{header}}
                            </h4>
                        </div>
                       <div class='modal-body'>
                           <table>
                               <thead>
                                    
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Sex</th>
                                    <th>Title</th>
                                    <th>ISBN</th>
                                    <th>Copy ID</th>
                                    <th>{{header}} Fine</th>
    
                                    
                                    
                               </thead>
                               <tbody>
                                   
                                   <tr>
                                        <td class='col-lg-1'>{{reader.ID}}</td>
                                        <td class='col-lg-1'>{{reader.name}}</td>
                                        <td class='col-lg-1'>{{sex_to_view(reader.sex)}}</td>
                                        <td class='col-lg-1'>{{copy.book.title}}</td>
                                        <td class='col-lg-1'>{{copy.book.ISBN}}</td>
                                        <td class='col-lg-1'>{{copy.copy_id}}</td>
               
                                        <td class='col-lg-1'>{{fine}}</td>
                                   </tr>
                                  
                               </tbody>
                           </table>

                       </div>
                        <div class="modal-footer">
                            <a class="btn btn-default" data-dismiss="modal" href='#' role='button'>Cancel
                            </a>
                            <a class="btn btn-default"  href='{{url_for('librarian.damage',reader_id=reader.reader_id,fine=fine)}}' role='button'>Submit
                            </a>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal -->
           
    </div>
    <div class='col-lg-4'></div>
</div>

{%endblock%}

webapp/templates/librarian/edit_reader.html
{%extends 'librarian/main.html'%}

{%block page_content%}
<div class='row'>
    </br></br>
    <div class='col-lg-2'>
            
    </div>
    <div class='col-lg-8'>
       
      
            {{wtf.quick_form(form)}}
     
            
    </div>
   
</div>
{%endblock%}